# Generated by Django 3.0.5 on 2020-06-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_baiviet_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
