# Generated by Django 3.0.5 on 2020-06-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200613_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
