# Generated by Django 3.0.8 on 2020-07-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_project_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baiviet',
            name='body',
        ),
    ]
